import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/sidebar/index";
import { getNodeToken, NodesData, NodesItem } from "../services/larkServices";
import Header from "../components/Header";
import Breadcrumb from "../components/Breadcrumb";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
async function getFileByFolderToken(folderNodes?: NodesItem[]) {
  let data, items;
  if (!folderNodes) {
    data = await getNodeToken();
    items = data.items;
  } else {
    items = folderNodes;
  }

  for (let i = 0; i < items.length; i++) {
    if (!items[i].children) {
      items[i].children = [];
    }
    if (items[i].has_child) {
      const child = (await getNodeToken(items[i].node_token)) as NodesData;
      items[i].children?.push(child);
      await getFileByFolderToken(child.items);
    }
  }
  return data as NodesData;
}

async function getMenu() {
  const data = await getFileByFolderToken();
  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await getMenu();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AntdRegistry>
          <main className="flex-1">
            <div className="border-b">
              <Header menu={menu} />
              <div className="pt-[50px] container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
                <Sidebar menu={menu} />
                <div>
                  <Breadcrumb menu={menu}></Breadcrumb>
                  {children}
                </div>
              </div>
            </div>
          </main>
        </AntdRegistry>
      </body>
    </html>
  );
}
